<a href="https://colab.research.google.com/github/Nukaraju2003/FundamentalsofMachineLearning/blob/main/Numpy1stQuestion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#2-D Numpy array of size (4,5)

Array = np.array([[1,2,3,4,5],
                 [6,7,8,9,10],
                 [11,12,13,14,15],
                 [16,17,18,19,20]])
print(Array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
# a.Modify elements less than 4 with -1 in the array
Array[Array<4]= -1
print("Modified Array: ")
print(Array)

Modified Array: 
[[-1 -1 -1  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
#b. Apply “sin” operation on every element in the array and multiple by 10.
result = np.sin(Array) * 10
print (result)

[[-8.41470985 -8.41470985 -8.41470985 -7.56802495 -9.58924275]
 [-2.79415498  6.56986599  9.89358247  4.12118485 -5.44021111]
 [-9.99990207 -5.36572918  4.20167037  9.90607356  6.5028784 ]
 [-2.87903317 -9.61397492 -7.50987247  1.4987721   9.12945251]]


In [ ]:
#c.Print 2 nd column from 2 nd and 3 rd row
selected_column = Array[1:3, 1]
print(selected_column)

[ 7 12]


In [ ]:
#d.Print element from last row and last column using negative indexing.
last_element = Array[-1,-1]
print(last_element)

20


In [ ]:
#e.Transpose a matrix
transposed_matrix = Array.T
print(transposed_matrix)

[[-1  6 11 16]
 [-1  7 12 17]
 [-1  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [ ]:
#f.Reshape the array into 2 rows and 10 columns
reshaped_Array = Array.reshape(2,10)
print(reshaped_Array)

[[-1 -1 -1  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [ ]:
#g. Print last row using negative indexing
lastrow = reshaped_Array[-1]
print(lastrow)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
#f.Convert a 2-D array into 1-D array. Flatten the array
flattenArray = reshaped_Array.flatten()
print(flattenArray)

[-1 -1 -1  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
