In [2]:
import numpy as np
import pandas as pd 


Numpy 

In [25]:
arr1 = np.arange(0,2)
arr2 = np.arange(6, 10).reshape(2, -1)
arr3 = np.array([[0,1],[1,0]])

arr1, arr2, arr3

(array([0, 1]),
 array([[6, 7],
        [8, 9]]),
 array([[0, 1],
        [1, 0]]))

Can you add arr1 and arr2? if so , explain the technique   

In [27]:
arr1 + arr2 + arr3

array([[ 6,  9],
       [ 9, 10]])

concatenation arr2 and arr3 (horizontally & vertically)

In [28]:
#horizontally 

np.concatenate((arr2, arr3), axis = 1)    #dimensionality 2rows*4columns

array([[6, 7, 0, 1],
       [8, 9, 1, 0]])

In [29]:
np.concatenate((arr2, arr3), axis=0)    #dimensionality 4rows*2columns

array([[6, 7],
       [8, 9],
       [0, 1],
       [1, 0]])

Find the index of the top 2 elements of [4, 1, 5, 7, 0]

In [4]:
np.argsort([24, 21, 25, 27, 20])

array([4, 1, 0, 2, 3], dtype=int64)

In [5]:
np.argsort([24, 21, 25, 27, 20])[-2:]

array([2, 3], dtype=int64)

Pandas

In [8]:
data = {'Name' : ['John', 'Emma', 'Luke', 'Emily', 'Oliver'],
        'Age' : [25, 28, 32, 21, 35],
        'Gender' : ['Male', 'Female', 'Male', 'Female', 'Male'], 
        'Salary' : [50000, 60000, 40000, 55000, 80000]}
df = pd.DataFrame(data)

In [9]:
df

Name  Age  Gender  Salary
0    John   25    Male   50000
1    Emma   28  Female   60000
2    Luke   32    Male   40000
3   Emily   21  Female   55000
4  Oliver   35    Male   80000

In [10]:
df.shape

(5, 4)

Select the rows where Age is between 25 and 30(both inclusive)

In [12]:
df.loc[(df['Age'] >=25) & (df['Age'] <=30)]

Name  Age  Gender  Salary
0  John   25    Male   50000
1  Emma   28  Female   60000

Find the maximum and median salary of Each Gender 

In [13]:
df.groupby("Gender").aggregate(max_salary = ('Salary', 'max'), median_salary = ('Salary', 'median'))

max_salary  median_salary
Gender                           
Female       60000        57500.0
Male         80000        50000.0

Apply a custom function to each Member, calculating a bonus based on their Age and Salary 
The  bonus should be 10% of the salary for individuals below the Age of 30 and 15% for individuals above or equal to the Age 30 

In [14]:
df['bonus'] = df[['Salary', 'Age']].apply(lambda x: 0.1*x['Salary'] 
                                          if x['Age'] < 30 
                                          else 0.15*x['Salary'], axis =1)

df

Name  Age  Gender  Salary    bonus
0    John   25    Male   50000   5000.0
1    Emma   28  Female   60000   6000.0
2    Luke   32    Male   40000   6000.0
3   Emily   21  Female   55000   5500.0
4  Oliver   35    Male   80000  12000.0

In [1]:
import pandas as pd 
df = pd.read_csv('D:\\practice\\FundamentalsofMachineLearning\\Numpy\\codebasics\\nyc_weather.csv')

# df.head()
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN   
1                10           7.0               0           3       NaN   
2                10           8.0               0           1       NaN   
3                10           9.0               0           3       NaN   
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
8                 9           8.0               T           8      Rain   
9                 4           NaN             1.8           7      Rain   
10               10           NaN               0           1       NaN   
11               10           6.0               T           4       NaN   
12               10          10.0               0           0       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1       NaN   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
21                9           NaN            0.01      

In [2]:
df['Temperature'].max()

50

In [3]:
df['EST'][df['Events'] == 'Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

## creating dictionary


In [4]:
import pandas as pd 

# df1 = pd.read_csv('D:\\practice\\FundamentalsofMachineLearning\\Numpy\\codebasics\\nyc_weather.csv')

# df1

weather_data = {
    'day' : ['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017'],
    'temperature' : [32,35,28,32],
    'windspeed' : [6,7,7,7],
    'event' : ['Rain', 'Sunny', 'snow', 'Rain']

}

df2 = pd.DataFrame(weather_data)
df2

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          7   snow
3  1/4/2017           32          7   Rain

In [5]:
df2.shape

(4, 4)

In [6]:
rows, columns = df2.shape  
rows

4

In [7]:
df2.head()

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          7   snow
3  1/4/2017           32          7   Rain

In [8]:
df2.head(2)

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny

In [9]:
df2.tail(2)

day  temperature  windspeed event
2  1/3/2017           28          7  snow
3  1/4/2017           32          7  Rain

In [10]:
df2[0:3]

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          7   snow

In [11]:
df2[:]

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          7   snow
3  1/4/2017           32          7   Rain

In [12]:
df2.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [13]:
df2.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
Name: day, dtype: object

In [14]:
df2.event     #df2['event']

0     Rain
1    Sunny
2     snow
3     Rain
Name: event, dtype: object